apiVersion: v1
kind: ResourceQuota
metadata:
  name: myrq
spec:
  hard:
    requests:
      cpu: "4"
      memory: "50Gi"
    limits:
      cpu: "8"
      memory: "100Gi"
    pods: "10"
    services: "5"
